version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hermes:
    build:
      context: ../hermes
      dockerfile: Dockerfile
    container_name: hermes
    volumes:
      - ./data:/root/data  # Mount your local data directory for CSV files
      - ./configs/hermes_config.yaml:/root/config/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  atalanta:
    build:
      context: ../atalanta
      dockerfile: Dockerfile
    container_name: atalanta
    volumes:
      - ./configs/atalanta_config.yaml:/root/config/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  hephaestus:
    build:
      context: ../hephaestus
      dockerfile: Dockerfile
    container_name: hephaestus
    volumes:
      - ./configs/hephaestus_config.yaml:/root/config/config.yaml
      - ./output/:/root/output/
    depends_on:
      rabbitmq:
        condition: service_healthy